services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  #Voters
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Domain\Api\UserControllerVoter:
    tags: [name: 'security.voter']

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Domain\Api\CsvControllerVoter:
    tags: [name: 'security.voter']

  #GetUserProfile
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUsername\GetUserByUsernameHandler:
    arguments:
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUsername\GetUserByUsernameService'
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUsername\GetUserByUsernameAssembler'
    tags:
    - {
        name: 'prooph_service_bus.auditor_framework_query_bus.route_target',
        message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUsername\GetUserByUsernameQuery
      }

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUsername\GetUserByUsernameService:
    arguments:
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Persistence\Doctrine\DoctrineUserReadModelRepository'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUsername\GetUserByUsernameAssembler:

  #GetUserIdProfile
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserIdByUsername\GetUserIdByUsernameHandler:
    arguments:
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserIdByUsername\GetUserIdByUsernameService'
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserIdByUsername\GetUserIdByUsernameAssembler'
    tags:
    - {
        name: 'prooph_service_bus.auditor_framework_query_bus.route_target',
        message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserIdByUsername\GetUserIdByUsernameQuery
      }

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserIdByUsername\GetUserIdByUsernameService:
    arguments:
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Persistence\Doctrine\DoctrineUserReadModelRepository'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserIdByUsername\GetUserIdByUsernameAssembler:

  #GetUserByUserId
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUserId\GetUserByUserIdHandler:
    arguments:
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUserId\GetUserByUserIdService'
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUserId\GetUserByUserIdAssembler'
    tags:
      - {
          name: 'prooph_service_bus.auditor_framework_query_bus.route_target',
          message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUserId\GetUserByUserIdQuery
        }

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUserId\GetUserByUserIdService:
    arguments:
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Persistence\Doctrine\DoctrineUserReadModelRepository'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\UserByUserId\GetUserByUserIdAssembler:

  #ForgotPasswordQueryHandler
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\ForgotPassword\GetPasswordRecoveryHandler:
    arguments:
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\ForgotPassword\GetPasswordRecoveryService'
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\ForgotPassword\PasswordRecoveryAssembler'
    tags:
    - {
        name: 'prooph_service_bus.auditor_framework_query_bus.route_target',
        message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\ForgotPassword\GetPasswordRecoveryQuery
      }

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\ForgotPassword\GetPasswordRecoveryService:
    arguments:
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Persistence\Doctrine\DoctrinePasswordRecoveryReadModelRepository'
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Persistence\Doctrine\DoctrineUserReadModelRepository'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Query\ForgotPassword\PasswordRecoveryAssembler:

  #AddRoleToUser
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\AddRoleToUser\AddRoleToUserService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\AddRoleToUser\AddRoleToUserHandler:
    tags:
    - {
        name: 'prooph_service_bus.auditor_framework_command_bus.route_target',
        message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\AddRoleToUser\AddRoleToUserCommand
      }

  #CreateUser
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\CreateUser\CreateUserService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\CreateUser\CreateUserHandler:
    tags:
    - {
        name: 'prooph_service_bus.auditor_framework_command_bus.route_target',
        message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\CreateUser\CreateUserCommand
      }

  #ChangePassword
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ChangePassword\ChangePasswordService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ChangePassword\ChangePasswordHandler:
    arguments:
      - '@TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ChangePassword\ChangePasswordService'
    tags:
    - {
        name: 'prooph_service_bus.auditor_framework_command_bus.route_target',
        message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ChangePassword\ChangePasswordCommand
      }

  ##ChangePassword
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ForgotPassword\ChangePassword\ChangePasswordService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ForgotPassword\ChangePassword\ChangePasswordHandler:
    tags:
      - {
          name: 'prooph_service_bus.auditor_framework_command_bus.route_target',
          message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ForgotPassword\ChangePassword\ChangePasswordCommand
        }

  ##CreateAndSendPasswordRecovery
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ForgotPassword\CreateAndSendPasswordRecovery\CreateAndSendPasswordRecoveryService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ForgotPassword\CreateAndSendPasswordRecovery\CreateAndSendPasswordRecoveryHandler:
    tags:
    - {
        name: 'prooph_service_bus.auditor_framework_command_bus.route_target',
        message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\ForgotPassword\CreateAndSendPasswordRecovery\CreateAndSendPasswordRecoveryCommand
      }

  ##BlockUser
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\BlockUser\BlockUserService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\BlockUser\BlockUserHandler:
    tags:
    - {
        name: 'prooph_service_bus.auditor_framework_command_bus.route_target',
        message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\BlockUser\BlockUserCommand
      }

  ##UnblockUser
  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\UnblockUser\UnblockUserService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\UnblockUser\UnblockUserHandler:
    tags:
    - {
        name: 'prooph_service_bus.auditor_framework_command_bus.route_target',
        message: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Application\Command\UnblockUser\UnblockUserCommand
      }
